analytics: {}
color:
  brandColors:
    - '#C8C0C8'
    - '#254560'
    - '#506090'
    - '#4078A8'
    - '#000000'
  brandStrength: 0.788884
  lightness: 0.275819
  rhythmicContrast: 0.024348
  saturation: 0.239919
cta: {}
layout_spectrum: 0.994932
name: Fitness Revolution Roswell
opengraph: {}
purpose: []
typography_spectrum: 0.487331
